// Generated by Copilot
export const nav_links = [
  {
    name: "Home Base",
    href: "/",
  },
  {
    name: "Trending Banget",
    href: "/trending",
  },
  {
    name: "Viral Parah",
    href: "/populer",
  },
  {
    name: "Articles",
    href: "/blog",
  },
  {
    name: "About Us",
    href: "/tentang",
  },
];

export const featured_news = [
  {
    id: 1,
    title: "iPhone 16 Bocor Lagi! Fitur AI-nya Bikin Speechless, Sih",
    excerpt:
      "Rumor iPhone 16 yang bakal drop tahun depan, guys. Katanya AI features-nya next level banget, auto mindblown!",
    category: "Tech",
    read_time: "3 min read",
    image_url: "/images/placeholder.webp",
    is_trending: true,
  },
  {
    id: 2,
    title:
      "Drama Twitter/X Terbaru: Elon Musk vs Mark Zuckerberg, Rematch Gak Sih?",
    excerpt:
      "Ada plot twist seru di dunia sosmed! Sekarang mereka debat soal AI sama masa depan internet, bro.",
    category: "Social Media",
    read_time: "5 min read",
    image_url: "",
    is_trending: false,
  },
  {
    id: 3,
    title: "Gen Z Mulai Move On dari Instagram? Survey-nya Bikin Kaget!",
    excerpt:
      "Ternyata platform favorit Gen Z udah shifting, loh! Kira-kira sekarang pada ke mana, ya?",
    category: "Lifestyle",
    read_time: "4 min read",
    image_url: "",
    is_trending: true,
  },
];
